### ISSUE TITLE
repo error

### ISSUE THREAD

**Issue by IIIdefconIII** [kempniu/kodivc#7]
iiidefconiii@htpc:~/kodivc-master$ sudo add-apt-repository -y universe
[sudo] password for iiidefconiii:

'universe' distribution component is already enabled for all sources.

iiidefconiii@htpc:~/kodivc-master$ sudo add-apt-repository -y ppa:kempniu/kodivc
gpg: keybox '/tmp/tmpr6sk8k3b/pubring.gpg' created

Error: retrieving gpg key timed out.
^C
gpg: signal Interrupt caught ... exiting
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by IIIdefconIII** [comment]
nvm after 6 times it finally worked
